### ISSUE TITLE
saber-windows-x64.exe is not statically linked

### ISSUE THREAD

**Issue by 115jon** [Xminent/saber#4]
This could be fixed by enabling the **-D net_FORCE_BUILD_OPENSSL=ON** flag to the x64 build as well. Or you could also fetch a newer version of OpenSSL by adding these steps like here:

```yaml
- name: Install OpenSSL
  if: runner.os == 'Windows'
  uses: johnwason/vcpkg-action@v5
  id: vcpkg
  with:
    pkgs: openssl
    triplet: x64-windows-static
    cache-key: ${{ runner.os }}-vcpkg
    token: ${{ github.token }}

- name: Add VCPKG_ROOT and OPENSSL env vars
  if: runner.os == 'Windows'
  run: |
    echo "OPENSSL_NO_VENDOR=1" | Out-File -FilePath $env:GITHUB_ENV -Append
    echo "OPENSSL_DIR=${{ github.workspace }}\vcpkg\installed\x64-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Append
    echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
```

But the easy way would just be editing the configure step to this:

```yaml
- name: Configure CMake (Windows x64)
        if: runner.os == 'Windows' && matrix.config.arch == 'x64'
        run: cmake -S . -B build -D net_FORCE_BUILD_OPENSSL=ON -G "Visual Studio 17 2022" -A x64 -T host=x64
```
